{
 "title": "RETIFICADORA [OLD]",
 "description": "Dashboard to display metrics",
 "tags": [ "snmp" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "query0",
    "label": "RETIFICADORA",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "description": "The time seconds since the network management portion of the system was last re-initialized.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "host": { "filter": "$query0" },
     "item": { "filter": "Uptime" },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "SELECT \"sysUpTime\"  / 100 FROM \"snmp.UPS\" WHERE (\"agent_host\" =~ /^$host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sysUpTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo restante da bateria",
   "type": "gauge",
   "description": "The time seconds since the network management portion of the system was last re-initialized.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "host": { "filter": "$query0" },
     "item": {
      "filter": "/(Tempo estimado para zerar a Bateria|Tempo Backup Bateria)/"
     },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "query": "SELECT \"sysUpTime\"  / 100 FROM \"snmp.UPS\" WHERE (\"agent_host\" =~ /^$host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "sysUpTime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Corrente de Carga do Sistema",
   "type": "bargauge",
   "description": "The magnitude of the system load current in units\nof 0.1A. Range between 0 to +10kA.",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": { "filter": "Corrente de Carga do Sistema" },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Modelo",
   "type": "stat",
   "description": "Modelo",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": { "filter": "System description" },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsBasicBatteryTimeOnBattery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Fabricante",
   "type": "stat",
   "description": "Manufacturer",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": { "filter": "PHB::identManufacturer" },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsBasicBatteryTimeOnBattery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Teste de Bateria",
   "type": "stat",
   "description": "Battery Test Alarm Status. It is ON when the Battery\n is being testing.\n \n (=1)ON (=2)OFF (=3)UNUSED",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": {
      "filter": "Status do alarme de teste de bateria"
     },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvTestDiagnosticsResults" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Control Unit Serial Number",
   "type": "stat",
   "description": "Control Unit Serial Number.",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": { "filter": "/Serial/" },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsBasicBatteryTimeOnBattery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Firmware Version",
   "type": "stat",
   "description": "The firmware (software) version of the controller.",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": {
      "filter": "PHB::identControllerFirmwareVersion"
     },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsBasicBatteryTimeOnBattery" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Battery Status",
   "type": "stat",
   "description": "Battery Alarm Status. It is ON when it happens\n a fail with Battery (String / Bank).\n \n (=1)ON (=2)OFF (=3)UNUSED",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": {
      "filter": "/(Status do alarme da bateria|Low Capacity, its owner: Battery1)/"
     },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvBatteryReplaceIndicator" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tensão de Saída",
   "type": "stat",
   "description": "The magnitude of the system output voltage in\nunits of 0.1V DC. Range -500V to +500V.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": {
      "filter": "/(Tensão de saída do Sistema|^Tensão de Saida DC$)/"
     },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "gauge",
   "description": "Cada Virgula separa uma UR, se o valor for XXX significa que está desativada.\nMultiplicar por x10 para a medida ficar em Ampere.\n\nThe magnitude of the system input voltage (Phase\n A) in units of 1V RMS, in single phase system\n this phase is the input voltage. Range between\n 0 to +500V. For Remote Power Feeding this measure\n is associated with the DC input A. In units of\n 0.1V DC. Range 0V to +1000V.",
   "gridPos": { "h": 12, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": {
      "filter": "/Corrente Modulos RU\\: [1-4]$/"
     },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:92",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$query0: (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/$query0: (.*)/, $1)"
      }
     ],
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": { "filter": "/Corrente Modulos RU\\: ./" },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:114",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$query0: (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/$query0: (.*)/, $1)"
      }
     ],
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": {
      "filter": "/Rectifier.\\: Corrente de saída DC/"
     },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ping Simples",
   "type": "stat",
   "description": "Ping Simples",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "description": "/.*Temperatura.*/\nStatus Sensor Temperatura da Bateria",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:61",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$query0: (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/$query0: (.*)/, $1)"
      }
     ],
     "group": { "filter": "RETIFICADORAS" },
     "host": { "filter": "$query0" },
     "item": { "filter": "/.*Temperatura.*/" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Capacidade da Bateria",
   "type": "timeseries",
   "description": "The remaining battery capacity expressed in\npercent of full capacity.",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:88",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$query0: (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/$query0: (.*)/, $1)"
      }
     ],
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" }
     ],
     "host": { "filter": "$query0" },
     "item": {
      "filter": "/Porcentagem da Bateria|Porcentagem Total das Baterias/"
     },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvBatteryCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo de resposta",
   "type": "stat",
   "description": "Tempo de resposta",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": { "filter": "ICMP response time" },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tensão de Entrada InputA",
   "type": "stat",
   "description": "The magnitude of the system input voltage (Phase\n A) in units of 1V RMS, in single phase system\n this phase is the input voltage. Range between\n 0 to +500V. For Remote Power Feeding this measure\n is associated with the DC input A. In units of\n 0.1V DC. Range 0V to +1000V.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": {
      "filter": "/(Tensão de entrada do Sistema Fase A|Tensão de fase da rede L1)/"
     },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Perda de Pacotes",
   "type": "stat",
   "description": "Perda de Pacotes",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": { "filter": "ICMP loss" },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tensão de Entrada InputB",
   "type": "stat",
   "description": "The magnitude of the system input voltage (Phase\n A) in units of 1V RMS, in single phase system\n this phase is the input voltage. Range between\n 0 to +500V. For Remote Power Feeding this measure\n is associated with the DC input A. In units of\n 0.1V DC. Range 0V to +1000V.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": {
      "filter": "/(Tensão de entrada do Sistema Fase B|Tensão de fase da rede L2)/"
     },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Corrente da Bateria",
   "type": "gauge",
   "description": "Corrente Total das Baterias\nThe magnitude of the system battery current in\nunits of 0.1A. Range between -5kA to +5kA.",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:61",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "/$query0: (.*)/",
        "$1"
       ],
       "text": "replaceAlias(/$query0: (.*)/, $1)"
      }
     ],
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": {
      "filter": "/(Corrente da Bateria|Corrente Total das Baterias)/"
     },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tensão de Entrada InputC",
   "type": "stat",
   "description": "The magnitude of the system input voltage (Phase\n C) in units of 1V RMS, in single phase system\n this phase is the input voltage. Range between\n 0 to +500V. For Remote Power Feeding this measure\n is associated with the DC input A. In units of\n 0.1V DC. Range 0V to +1000V.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_agent_host",
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "agent_host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "host": { "filter": "$query0" },
     "item": {
      "filter": "/(Tensão de entrada do Sistema Fase C|Tensão de fase da rede L3)/"
     },
     "itemTag": { "filter": "" },
     "measurement": "snmp.UPS",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "select": [
      [
       { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Eventos",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "RETIFICADORAS" },
     "host": { "filter": "$query0" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 4
     }
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Corrente Modulos RU: 1",
     "type": "gauge",
     "description": "Cada Virgula separa uma UR, se o valor for XXX significa que está desativada.\nMultiplicar por x10 para a medida ficar em Ampere.\n\nThe magnitude of the system input voltage (Phase\n A) in units of 1V RMS, in single phase system\n this phase is the input voltage. Range between\n 0 to +500V. For Remote Power Feeding this measure\n is associated with the DC input A. In units of\n 0.1V DC. Range 0V to +1000V.",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_agent_host",
       "application": { "filter": "" },
       "group": { "filter": "RETIFICADORAS" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent_host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "host": { "filter": "$query0" },
       "item": { "filter": "Corrente Modulos RU: 1" },
       "itemTag": { "filter": "" },
       "measurement": "snmp.UPS",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "select": [
        [
         { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "alias": "$tag_agent_host",
       "application": { "filter": "" },
       "group": { "filter": "RETIFICADORAS" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent_host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "host": { "filter": "$query0" },
       "item": { "filter": "Corrente Modulos RU: 1" },
       "itemTag": { "filter": "" },
       "measurement": "snmp.UPS",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "select": [
        [
         { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Corrente Modulos RU: 2",
     "type": "gauge",
     "description": "Cada Virgula separa uma UR, se o valor for XXX significa que está desativada.\nMultiplicar por x10 para a medida ficar em Ampere.\n\nThe magnitude of the system input voltage (Phase\n A) in units of 1V RMS, in single phase system\n this phase is the input voltage. Range between\n 0 to +500V. For Remote Power Feeding this measure\n is associated with the DC input A. In units of\n 0.1V DC. Range 0V to +1000V.",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_agent_host",
       "application": { "filter": "" },
       "group": { "filter": "RETIFICADORAS" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent_host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "host": { "filter": "$query0" },
       "item": { "filter": "Corrente Modulos RU: 2" },
       "itemTag": { "filter": "" },
       "measurement": "snmp.UPS",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "select": [
        [
         { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "alias": "$tag_agent_host",
       "application": { "filter": "" },
       "group": { "filter": "RETIFICADORAS" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent_host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "host": { "filter": "$query0" },
       "item": { "filter": "Corrente Modulos RU: 2" },
       "itemTag": { "filter": "" },
       "measurement": "snmp.UPS",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "select": [
        [
         { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Corrente Modulos RU: 3",
     "type": "gauge",
     "description": "Cada Virgula separa uma UR, se o valor for XXX significa que está desativada.\nMultiplicar por x10 para a medida ficar em Ampere.\n\nThe magnitude of the system input voltage (Phase\n A) in units of 1V RMS, in single phase system\n this phase is the input voltage. Range between\n 0 to +500V. For Remote Power Feeding this measure\n is associated with the DC input A. In units of\n 0.1V DC. Range 0V to +1000V.",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_agent_host",
       "application": { "filter": "" },
       "group": { "filter": "RETIFICADORAS" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent_host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "host": { "filter": "$query0" },
       "item": { "filter": "Corrente Modulos RU: 3" },
       "itemTag": { "filter": "" },
       "measurement": "snmp.UPS",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "select": [
        [
         { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "alias": "$tag_agent_host",
       "application": { "filter": "" },
       "group": { "filter": "RETIFICADORAS" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent_host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "host": { "filter": "$query0" },
       "item": { "filter": "Corrente Modulos RU: 3" },
       "itemTag": { "filter": "" },
       "measurement": "snmp.UPS",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "select": [
        [
         { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Corrente Modulos RU: 4",
     "type": "gauge",
     "description": "Cada Virgula separa uma UR, se o valor for XXX significa que está desativada.\nMultiplicar por x10 para a medida ficar em Ampere.\n\nThe magnitude of the system input voltage (Phase\n A) in units of 1V RMS, in single phase system\n this phase is the input voltage. Range between\n 0 to +500V. For Remote Power Feeding this measure\n is associated with the DC input A. In units of\n 0.1V DC. Range 0V to +1000V.",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_agent_host",
       "application": { "filter": "" },
       "group": { "filter": "RETIFICADORAS" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent_host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "host": { "filter": "$query0" },
       "item": { "filter": "Corrente Modulos RU: 4" },
       "itemTag": { "filter": "" },
       "measurement": "snmp.UPS",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "select": [
        [
         { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      },
      {
       "alias": "$tag_agent_host",
       "application": { "filter": "" },
       "group": { "filter": "RETIFICADORAS" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "agent_host" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "host": { "filter": "$query0" },
       "item": { "filter": "Corrente Modulos RU: 4" },
       "itemTag": { "filter": "" },
       "measurement": "snmp.UPS",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "select": [
        [
         { "params": [ "upsAdvOutputActivePower" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 33 },
     "options": {
      "content": "<p style=\"text-align:center; vertical-align: middle;\">\r\n<img src=\"https://br.all.biz/img/br/catalog/37975.jpeg\" style=\"background-color:blue\" height=\"125\" alt=\"CONECT\"/>\r\n</p>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Status dos Alarmes",
     "type": "stat",
     "description": "VERDE = ALARME OFF\nVERMELHO = ALARME ON  \nCINZA = ALARME DESATIVADO",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "$$hashKey": "object:581",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/$query0: Status do alarme (.*)/",
          "$1"
         ],
         "text": "replaceAlias(/$query0: Status do alarme (.*)/, $1)"
        },
        {
         "$$hashKey": "object:582",
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/de|do|da (.*)/",
          "$1"
         ],
         "text": "replaceAlias(/de|do|da (.*)/, $1)"
        }
       ],
       "group": { "filter": "RETIFICADORAS" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "host": { "filter": "$query0" },
       "item": { "filter": "/Status do alarme/" },
       "itemTag": { "filter": "" },
       "measurement": "snmp.UPS",
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "select": [
        [
         { "params": [ "upsAdvTestDiagnosticsResults" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ],
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  }
 ]
}